In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e10/sample_submission.csv
/kaggle/input/playground-series-s5e10/train.csv
/kaggle/input/playground-series-s5e10/test.csv

In [23]:
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [4]:
data = pd.read_csv('/kaggle/input/playground-series-s5e10/train.csv')
data.drop(['id'], inplace=True, axis=1)

In [6]:
data.head()

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56

In [7]:
data.isnull().sum()

road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
accident_risk             0
dtype: int64

In [8]:
num_cols = make_column_selector(dtype_include='number')
cat_cols = make_column_selector(dtype_include=['object', 'bool'])

In [9]:
data[num_cols].columns

Index(['num_lanes', 'curvature', 'speed_limit', 'num_reported_accidents',
       'accident_risk'],
      dtype='object')

In [10]:
data[cat_cols].columns

Index(['road_type', 'lighting', 'weather', 'road_signs_present', 'public_road',
       'time_of_day', 'holiday', 'school_season'],
      dtype='object')

In [11]:
X = data.drop(['accident_risk'], axis=1)
y = data['accident_risk'].values

# Encoding and scaling

In [12]:
cat_pipe = Pipeline([
    ('cat', OneHotEncoder())
])

num_pipe = Pipeline([
    ('num', StandardScaler())
])

ctx = ColumnTransformer([
    ('cat', cat_pipe, cat_cols),
    ('num', num_pipe, num_cols)
], remainder='passthrough')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = ctx.fit_transform(X_train)
X_test = ctx.transform(X_test)

# Catboost

In [14]:
cat = CatBoostRegressor(verbose=0)
cat.fit(X_train, y_train)
y_pred = cat.predict(X_test)

print('MSE for catboost:', mean_squared_error(y_test, y_pred))
print('R2 for catboost:', r2_score(y_test, y_pred))

MSE for catboost: 0.0031612873982016193
R2 for catboost: 0.8855111850975814

In [ ]:
param_distributions = {
    'iterations': [200, 400, 800, 1200, 1600],
    'learning_rate': [0.01, 0.03, 0.05, 0.1, 0.2],
    'depth': [4, 5, 6, 7, 8, 9, 10],
    'l2_leaf_reg': [1, 3, 5, 7, 9, 11, 13],
    'bagging_temperature': [0, 0.25, 0.5, 0.75, 1.0],
    'border_count': [32, 64, 128, 254],
    'random_strength': [0.5, 1, 2, 5, 10],
    'leaf_estimation_iterations': [1, 3, 5, 7, 9],
    'grow_policy': ['SymmetricTree', 'Depthwise', 'Lossguide'],
    'bootstrap_type': ['Bayesian', 'Bernoulli', 'MVS'],
    'subsample': [0.6, 0.8, 1.0],
    'min_data_in_leaf': [1, 5, 10, 20, 50, 100]
}

randomCv = RandomizedSearchCV(
    estimator=CatBoostRegressor(verbose=0),
    param_distributions=param_distributions,
    cv = 5,
    n_iter=50,
    scoring='neg_mean_squared_error',
    random_state=42,
    n_jobs=-1
)

ctx2 = ColumnTransformer([
    ('cat', cat_pipe, cat_cols),
    ('num', num_pipe, num_cols)
], remainder='passthrough')

X_transformed = ctx2.fit_transform(X)
gcv = randomCv.fit(X_transformed, y, verbose=1)

In [16]:
print('best params:', gcv.best_params_)
print('best score:', gcv.best_score_)

best params: {'subsample': 1.0, 'random_strength': 5, 'min_data_in_leaf': 10, 'learning_rate': 0.1, 'leaf_estimation_iterations': 1, 'l2_leaf_reg': 5, 'iterations': 800, 'grow_policy': 'SymmetricTree', 'depth': 7, 'border_count': 128, 'bootstrap_type': 'MVS', 'bagging_temperature': 0.5}
best score: -0.003144248898098992
1571:	learn: 0.0563165	total: 6m 23s	remaining: 6.82s
1572:	learn: 0.0563162	total: 6m 23s	remaining: 6.58s
1573:	learn: 0.0563161	total: 6m 23s	remaining: 6.34s
1574:	learn: 0.0563158	total: 6m 23s	remaining: 6.09s
1575:	learn: 0.0563155	total: 6m 24s	remaining: 5.85s
1576:	learn: 0.0563153	total: 6m 24s	remaining: 5.61s
1577:	learn: 0.0563152	total: 6m 24s	remaining: 5.36s
1578:	learn: 0.0563150	total: 6m 24s	remaining: 5.12s
1579:	learn: 0.0563148	total: 6m 25s	remaining: 4.87s
1580:	learn: 0.0563146	total: 6m 25s	remaining: 4.63s
1581:	learn: 0.0563144	total: 6m 25s	remaining: 4.39s
1582:	learn: 0.0563142	total: 6m 25s	remaining: 4.14s
1583:	learn: 0.0563140	total: 6m 26s	remaining: 3.9s
1584:	learn: 0.0563138	total: 6m 26s	remaining: 3.65s
1585:	learn: 0.0563136	total: 6m 26s	remaining: 3.41s
1586:	learn: 0.0563134	total: 6m 26s	remaining: 3.17s
1587:	learn: 0.0563132	total: 6m 26s	remaining: 2.92s
1588:	learn: 0.0563131	total: 6m 27s	remaining: 2.68s
1589:	learn: 0.0563130	total: 6m 27s	remaining: 2.44s
1590:	learn: 0.0563127	total: 6m 27s	remaining: 2.19s
1591:	learn: 0.0563124	total: 6m 27s	remaining: 1.95s
1592:	learn: 0.0563122	total: 6m 27s	remaining: 1.7s
1593:	learn: 0.0563120	total: 6m 28s	remaining: 1.46s
1594:	learn: 0.0563118	total: 6m 28s	remaining: 1.22s
1595:	learn: 0.0563116	total: 6m 28s	remaining: 974ms
1596:	learn: 0.0563114	total: 6m 28s	remaining: 730ms
1597:	learn: 0.0563112	total: 6m 28s	remaining: 487ms
1598:	learn: 0.0563110	total: 6m 29s	remaining: 243ms
1599:	learn: 0.0563109	total: 6m 29s	remaining: 0us
1482:	learn: 0.0564720	total: 6m 4s	remaining: 28.8s
1483:	learn: 0.0564717	total: 6m 4s	remaining: 28.5s
1484:	learn: 0.0564714	total: 6m 5s	remaining: 28.3s
1485:	learn: 0.0564711	total: 6m 5s	remaining: 28s
1486:	learn: 0.0564709	total: 6m 5s	remaining: 27.8s
1487:	learn: 0.0564705	total: 6m 5s	remaining: 27.5s
1488:	learn: 0.0564703	total: 6m 6s	remaining: 27.3s
1489:	learn: 0.0564700	total: 6m 6s	remaining: 27s
1490:	learn: 0.0564697	total: 6m 6s	remaining: 26.8s
1491:	learn: 0.0564695	total: 6m 6s	remaining: 26.6s
1492:	learn: 0.0564693	total: 6m 7s	remaining: 26.3s
1493:	learn: 0.0564689	total: 6m 7s	remaining: 26.1s
1494:	learn: 0.0564687	total: 6m 7s	remaining: 25.8s
1495:	learn: 0.0564684	total: 6m 7s	remaining: 25.6s
1496:	learn: 0.0564683	total: 6m 7s	remaining: 25.3s
1497:	learn: 0.0564682	total: 6m 8s	remaining: 25.1s
1498:	learn: 0.0564678	total: 6m 8s	remaining: 24.8s
1499:	learn: 0.0564675	total: 6m 8s	remaining: 24.6s
1500:	learn: 0.0564673	total: 6m 8s	remaining: 24.3s
1501:	learn: 0.0564671	total: 6m 9s	remaining: 24.1s
1502:	learn: 0.0564668	total: 6m 9s	remaining: 23.8s
1503:	learn: 0.0564666	total: 6m 9s	remaining: 23.6s
1504:	learn: 0.0564664	total: 6m 9s	remaining: 23.4s
1505:	learn: 0.0564663	total: 6m 10s	remaining: 23.1s
1506:	learn: 0.0564661	total: 6m 10s	remaining: 22.9s
1507:	learn: 0.0564660	total: 6m 10s	remaining: 22.6s
1508:	learn: 0.0564658	total: 6m 10s	remaining: 22.4s
1509:	learn: 0.0564656	total: 6m 11s	remaining: 22.1s
1510:	learn: 0.0564653	total: 6m 11s	remaining: 21.9s
1511:	learn: 0.0564650	total: 6m 11s	remaining: 21.6s
1512:	learn: 0.0564648	total: 6m 11s	remaining: 21.4s
1513:	learn: 0.0564646	total: 6m 12s	remaining: 21.1s
1514:	learn: 0.0564645	total: 6m 12s	remaining: 20.9s
1515:	learn: 0.0564641	total: 6m 12s	remaining: 20.6s
1516:	learn: 0.0564640	total: 6m 12s	remaining: 20.4s
1517:	learn: 0.0564637	total: 6m 13s	remaining: 20.1s
1518:	learn: 0.0564636	total: 6m 13s	remaining: 19.9s
1519:	learn: 0.0564633	total: 6m 13s	remaining: 19.7s
1520:	learn: 0.0564631	total: 6m 13s	remaining: 19.4s
1521:	learn: 0.0564628	total: 6m 14s	remaining: 19.2s
1522:	learn: 0.0564625	total: 6m 14s	remaining: 18.9s
1523:	learn: 0.0564622	total: 6m 14s	remaining: 18.7s
1524:	learn: 0.0564619	total: 6m 14s	remaining: 18.4s
1525:	learn: 0.0564617	total: 6m 14s	remaining: 18.2s
1526:	learn: 0.0564616	total: 6m 15s	remaining: 17.9s
1527:	learn: 0.0564615	total: 6m 15s	remaining: 17.7s
1528:	learn: 0.0564613	total: 6m 15s	remaining: 17.4s
1529:	learn: 0.0564610	total: 6m 15s	remaining: 17.2s
1530:	learn: 0.0564608	total: 6m 16s	remaining: 17s
1531:	learn: 0.0564606	total: 6m 16s	remaining: 16.7s
1532:	learn: 0.0564603	total: 6m 16s	remaining: 16.5s
1533:	learn: 0.0564600	total: 6m 16s	remaining: 16.2s
1534:	learn: 0.0564596	total: 6m 17s	remaining: 16s
1535:	learn: 0.0564594	total: 6m 17s	remaining: 15.7s
1536:	learn: 0.0564591	total: 6m 17s	remaining: 15.5s
1537:	learn: 0.0564589	total: 6m 17s	remaining: 15.2s
1538:	learn: 0.0564587	total: 6m 18s	remaining: 15s
1539:	learn: 0.0564585	total: 6m 18s	remaining: 14.7s
1540:	learn: 0.0564582	total: 6m 18s	remaining: 14.5s
1541:	learn: 0.0564579	total: 6m 18s	remaining: 14.3s
1542:	learn: 0.0564577	total: 6m 19s	remaining: 14s
1543:	learn: 0.0564574	total: 6m 19s	remaining: 13.8s
1544:	learn: 0.0564572	total: 6m 19s	remaining: 13.5s
1545:	learn: 0.0564571	total: 6m 19s	remaining: 13.3s
1546:	learn: 0.0564569	total: 6m 20s	remaining: 13s
1547:	learn: 0.0564567	total: 6m 20s	remaining: 12.8s
1548:	learn: 0.0564566	total: 6m 20s	remaining: 12.5s
1549:	learn: 0.0564562	total: 6m 20s	remaining: 12.3s
1550:	learn: 0.0564560	total: 6m 21s	remaining: 12s
1551:	learn: 0.0564559	total: 6m 21s	remaining: 11.8s
1552:	learn: 0.0564557	total: 6m 21s	remaining: 11.5s
1553:	learn: 0.0564555	total: 6m 21s	remaining: 11.3s
1554:	learn: 0.0564553	total: 6m 22s	remaining: 11.1s
1555:	learn: 0.0564551	total: 6m 22s	remaining: 10.8s
1556:	learn: 0.0564550	total: 6m 22s	remaining: 10.6s
1557:	learn: 0.0564549	total: 6m 22s	remaining: 10.3s
1558:	learn: 0.0564546	total: 6m 23s	remaining: 10.1s
1559:	learn: 0.0564544	total: 6m 23s	remaining: 9.83s
1560:	learn: 0.0564543	total: 6m 23s	remaining: 9.58s
1561:	learn: 0.0564541	total: 6m 23s	remaining: 9.34s
1562:	learn: 0.0564540	total: 6m 23s	remaining: 9.09s
1563:	learn: 0.0564537	total: 6m 24s	remaining: 8.85s
1564:	learn: 0.0564536	total: 6m 24s	remaining: 8.6s
1565:	learn: 0.0564533	total: 6m 24s	remaining: 8.35s
1566:	learn: 0.0564531	total: 6m 25s	remaining: 8.11s
1567:	learn: 0.0564530	total: 6m 25s	remaining: 7.86s
1568:	learn: 0.0564528	total: 6m 25s	remaining: 7.62s
1569:	learn: 0.0564525	total: 6m 25s	remaining: 7.37s
1570:	learn: 0.0564523	total: 6m 25s	remaining: 7.13s
1571:	learn: 0.0564520	total: 6m 26s	remaining: 6.88s
1572:	learn: 0.0564517	total: 6m 26s	remaining: 6.63s
1573:	learn: 0.0564515	total: 6m 26s	remaining: 6.39s
1574:	learn: 0.0564513	total: 6m 27s	remaining: 6.14s
1575:	learn: 0.0564511	total: 6m 27s	remaining: 5.9s
1576:	learn: 0.0564509	total: 6m 27s	remaining: 5.65s
1577:	learn: 0.0564507	total: 6m 27s	remaining: 5.41s
1578:	learn: 0.0564505	total: 6m 28s	remaining: 5.16s
1579:	learn: 0.0564503	total: 6m 28s	remaining: 4.91s
1580:	learn: 0.0564501	total: 6m 28s	remaining: 4.67s
1581:	learn: 0.0564499	total: 6m 28s	remaining: 4.42s
1582:	learn: 0.0564498	total: 6m 28s	remaining: 4.18s
1583:	learn: 0.0564496	total: 6m 29s	remaining: 3.93s
1584:	learn: 0.0564494	total: 6m 29s	remaining: 3.68s
1585:	learn: 0.0564491	total: 6m 29s	remaining: 3.44s
1586:	learn: 0.0564489	total: 6m 29s	remaining: 3.19s
1587:	learn: 0.0564486	total: 6m 30s	remaining: 2.95s
1588:	learn: 0.0564484	total: 6m 30s	remaining: 2.7s
1589:	learn: 0.0564482	total: 6m 30s	remaining: 2.46s
1590:	learn: 0.0564480	total: 6m 30s	remaining: 2.21s
1591:	learn: 0.0564477	total: 6m 31s	remaining: 1.97s
1592:	learn: 0.0564475	total: 6m 31s	remaining: 1.72s
1593:	learn: 0.0564474	total: 6m 31s	remaining: 1.47s
1594:	learn: 0.0564470	total: 6m 31s	remaining: 1.23s
1595:	learn: 0.0564467	total: 6m 31s	remaining: 982ms
1596:	learn: 0.0564465	total: 6m 31s	remaining: 736ms
1597:	learn: 0.0564462	total: 6m 32s	remaining: 491ms
1598:	learn: 0.0564460	total: 6m 32s	remaining: 245ms
1599:	learn: 0.0564457	total: 6m 32s	remaining: 0us
1534:	learn: 0.0563511	total: 5m 45s	remaining: 14.6s
1535:	learn: 0.0563508	total: 5m 45s	remaining: 14.4s
1536:	learn: 0.0563506	total: 5m 45s	remaining: 14.2s
1537:	learn: 0.0563503	total: 5m 45s	remaining: 13.9s
1538:	learn: 0.0563501	total: 5m 45s	remaining: 13.7s
1539:	learn: 0.0563498	total: 5m 46s	remaining: 13.5s
1540:	learn: 0.0563496	total: 5m 46s	remaining: 13.3s
1541:	learn: 0.0563494	total: 5m 46s	remaining: 13s
1542:	learn: 0.0563492	total: 5m 46s	remaining: 12.8s
1543:	learn: 0.0563490	total: 5m 46s	remaining: 12.6s
1544:	learn: 0.0563488	total: 5m 46s	remaining: 12.3s
1545:	learn: 0.0563485	total: 5m 46s	remaining: 12.1s
1546:	learn: 0.0563484	total: 5m 46s	remaining: 11.9s
1547:	learn: 0.0563482	total: 5m 46s	remaining: 11.7s
1548:	learn: 0.0563480	total: 5m 47s	remaining: 11.4s
1549:	learn: 0.0563477	total: 5m 47s	remaining: 11.2s
1550:	learn: 0.0563475	total: 5m 47s	remaining: 11s
1551:	learn: 0.0563472	total: 5m 47s	remaining: 10.7s
1552:	learn: 0.0563470	total: 5m 47s	remaining: 10.5s
1553:	learn: 0.0563468	total: 5m 47s	remaining: 10.3s
1554:	learn: 0.0563467	total: 5m 47s	remaining: 10.1s
1555:	learn: 0.0563465	total: 5m 47s	remaining: 9.83s
1556:	learn: 0.0563464	total: 5m 47s	remaining: 9.61s
1557:	learn: 0.0563461	total: 5m 48s	remaining: 9.38s
1558:	learn: 0.0563458	total: 5m 48s	remaining: 9.15s
1559:	learn: 0.0563456	total: 5m 48s	remaining: 8.93s
1560:	learn: 0.0563453	total: 5m 48s	remaining: 8.7s
1561:	learn: 0.0563451	total: 5m 48s	remaining: 8.48s
1562:	learn: 0.0563448	total: 5m 48s	remaining: 8.25s
1563:	learn: 0.0563446	total: 5m 48s	remaining: 8.03s
1564:	learn: 0.0563445	total: 5m 48s	remaining: 7.8s
1565:	learn: 0.0563443	total: 5m 48s	remaining: 7.57s
1566:	learn: 0.0563440	total: 5m 48s	remaining: 7.35s
1567:	learn: 0.0563437	total: 5m 49s	remaining: 7.12s
1568:	learn: 0.0563434	total: 5m 49s	remaining: 6.9s
1569:	learn: 0.0563431	total: 5m 49s	remaining: 6.67s
1570:	learn: 0.0563428	total: 5m 49s	remaining: 6.45s
1571:	learn: 0.0563425	total: 5m 49s	remaining: 6.23s
1572:	learn: 0.0563422	total: 5m 49s	remaining: 6s
1573:	learn: 0.0563420	total: 5m 49s	remaining: 5.78s
1574:	learn: 0.0563417	total: 5m 50s	remaining: 5.56s
1575:	learn: 0.0563415	total: 5m 50s	remaining: 5.33s
1576:	learn: 0.0563414	total: 5m 50s	remaining: 5.11s
1577:	learn: 0.0563411	total: 5m 50s	remaining: 4.88s
1578:	learn: 0.0563409	total: 5m 50s	remaining: 4.66s
1579:	learn: 0.0563407	total: 5m 50s	remaining: 4.44s
1580:	learn: 0.0563405	total: 5m 50s	remaining: 4.21s
1581:	learn: 0.0563402	total: 5m 50s	remaining: 3.99s
1582:	learn: 0.0563399	total: 5m 50s	remaining: 3.77s
1583:	learn: 0.0563397	total: 5m 51s	remaining: 3.54s
1584:	learn: 0.0563395	total: 5m 51s	remaining: 3.32s
1585:	learn: 0.0563391	total: 5m 51s	remaining: 3.1s
1586:	learn: 0.0563389	total: 5m 51s	remaining: 2.88s
1587:	learn: 0.0563386	total: 5m 51s	remaining: 2.65s
1588:	learn: 0.0563384	total: 5m 51s	remaining: 2.43s
1589:	learn: 0.0563382	total: 5m 51s	remaining: 2.21s
1590:	learn: 0.0563380	total: 5m 51s	remaining: 1.99s
1591:	learn: 0.0563378	total: 5m 51s	remaining: 1.77s
1592:	learn: 0.0563376	total: 5m 51s	remaining: 1.55s
1593:	learn: 0.0563373	total: 5m 52s	remaining: 1.32s
1594:	learn: 0.0563372	total: 5m 52s	remaining: 1.1s
1595:	learn: 0.0563369	total: 5m 52s	remaining: 883ms
1596:	learn: 0.0563367	total: 5m 52s	remaining: 662ms
1597:	learn: 0.0563365	total: 5m 52s	remaining: 441ms
1598:	learn: 0.0563362	total: 5m 52s	remaining: 221ms
1599:	learn: 0.0563360	total: 5m 52s	remaining: 0us
1507:	learn: 0.0564338	total: 1m 28s	remaining: 5.39s
1508:	learn: 0.0564336	total: 1m 28s	remaining: 5.33s
1509:	learn: 0.0564334	total: 1m 28s	remaining: 5.27s
1510:	learn: 0.0564331	total: 1m 28s	remaining: 5.21s
1511:	learn: 0.0564330	total: 1m 28s	remaining: 5.16s
1512:	learn: 0.0564328	total: 1m 28s	remaining: 5.1s
1513:	learn: 0.0564326	total: 1m 28s	remaining: 5.04s
1514:	learn: 0.0564322	total: 1m 28s	remaining: 4.98s
1515:	learn: 0.0564320	total: 1m 28s	remaining: 4.92s
1516:	learn: 0.0564317	total: 1m 28s	remaining: 4.86s
1517:	learn: 0.0564315	total: 1m 28s	remaining: 4.8s
1518:	learn: 0.0564311	total: 1m 28s	remaining: 4.74s
1519:	learn: 0.0564310	total: 1m 28s	remaining: 4.68s
1520:	learn: 0.0564308	total: 1m 29s	remaining: 4.62s
1521:	learn: 0.0564306	total: 1m 29s	remaining: 4.56s
1522:	learn: 0.0564304	total: 1m 29s	remaining: 4.5s
1523:	learn: 0.0564303	total: 1m 29s	remaining: 4.45s
1524:	learn: 0.0564301	total: 1m 29s	remaining: 4.39s
1525:	learn: 0.0564300	total: 1m 29s	remaining: 4.33s
1526:	learn: 0.0564298	total: 1m 29s	remaining: 4.27s
1527:	learn: 0.0564296	total: 1m 29s	remaining: 4.21s
1528:	learn: 0.0564293	total: 1m 29s	remaining: 4.15s
1529:	learn: 0.0564291	total: 1m 29s	remaining: 4.09s
1530:	learn: 0.0564287	total: 1m 29s	remaining: 4.03s
1531:	learn: 0.0564285	total: 1m 29s	remaining: 3.97s
1532:	learn: 0.0564282	total: 1m 29s	remaining: 3.92s
1533:	learn: 0.0564280	total: 1m 29s	remaining: 3.86s
1534:	learn: 0.0564277	total: 1m 29s	remaining: 3.8s
1535:	learn: 0.0564276	total: 1m 29s	remaining: 3.74s
1536:	learn: 0.0564273	total: 1m 29s	remaining: 3.68s
1537:	learn: 0.0564271	total: 1m 29s	remaining: 3.62s
1538:	learn: 0.0564266	total: 1m 29s	remaining: 3.56s
1539:	learn: 0.0564264	total: 1m 29s	remaining: 3.5s
1540:	learn: 0.0564261	total: 1m 29s	remaining: 3.44s
1541:	learn: 0.0564260	total: 1m 30s	remaining: 3.39s
1542:	learn: 0.0564257	total: 1m 30s	remaining: 3.33s
1543:	learn: 0.0564254	total: 1m 30s	remaining: 3.27s
1544:	learn: 0.0564252	total: 1m 30s	remaining: 3.21s
1545:	learn: 0.0564249	total: 1m 30s	remaining: 3.15s
1546:	learn: 0.0564247	total: 1m 30s	remaining: 3.09s
1547:	learn: 0.0564245	total: 1m 30s	remaining: 3.03s
1548:	learn: 0.0564243	total: 1m 30s	remaining: 2.98s
1549:	learn: 0.0564241	total: 1m 30s	remaining: 2.92s
1550:	learn: 0.0564238	total: 1m 30s	remaining: 2.86s
1551:	learn: 0.0564235	total: 1m 30s	remaining: 2.8s
1552:	learn: 0.0564233	total: 1m 30s	remaining: 2.74s
1553:	learn: 0.0564232	total: 1m 30s	remaining: 2.68s
1554:	learn: 0.0564230	total: 1m 30s	remaining: 2.62s
1555:	learn: 0.0564227	total: 1m 30s	remaining: 2.56s
1556:	learn: 0.0564225	total: 1m 30s	remaining: 2.51s
1557:	learn: 0.0564223	total: 1m 30s	remaining: 2.45s
1558:	learn: 0.0564222	total: 1m 30s	remaining: 2.39s
1559:	learn: 0.0564219	total: 1m 30s	remaining: 2.33s
1560:	learn: 0.0564216	total: 1m 30s	remaining: 2.27s
1561:	learn: 0.0564213	total: 1m 31s	remaining: 2.21s
1562:	learn: 0.0564211	total: 1m 31s	remaining: 2.15s
1563:	learn: 0.0564209	total: 1m 31s	remaining: 2.1s
1564:	learn: 0.0564206	total: 1m 31s	remaining: 2.04s
1565:	learn: 0.0564205	total: 1m 31s	remaining: 1.98s
1566:	learn: 0.0564203	total: 1m 31s	remaining: 1.92s
1567:	learn: 0.0564201	total: 1m 31s	remaining: 1.86s
1568:	learn: 0.0564199	total: 1m 31s	remaining: 1.8s
1569:	learn: 0.0564196	total: 1m 31s	remaining: 1.75s
1570:	learn: 0.0564193	total: 1m 31s	remaining: 1.69s
1571:	learn: 0.0564192	total: 1m 31s	remaining: 1.63s
1572:	learn: 0.0564190	total: 1m 31s	remaining: 1.57s
1573:	learn: 0.0564188	total: 1m 31s	remaining: 1.51s
1574:	learn: 0.0564186	total: 1m 31s	remaining: 1.45s
1575:	learn: 0.0564183	total: 1m 31s	remaining: 1.4s
1576:	learn: 0.0564181	total: 1m 31s	remaining: 1.34s
1577:	learn: 0.0564179	total: 1m 31s	remaining: 1.28s
1578:	learn: 0.0564176	total: 1m 31s	remaining: 1.22s
1579:	learn: 0.0564175	total: 1m 31s	remaining: 1.16s
1580:	learn: 0.0564172	total: 1m 31s	remaining: 1.1s
1581:	learn: 0.0564170	total: 1m 31s	remaining: 1.05s
1582:	learn: 0.0564167	total: 1m 32s	remaining: 988ms
1583:	learn: 0.0564165	total: 1m 32s	remaining: 930ms
1584:	learn: 0.0564162	total: 1m 32s	remaining: 872ms
1585:	learn: 0.0564161	total: 1m 32s	remaining: 813ms
1586:	learn: 0.0564158	total: 1m 32s	remaining: 755ms
1587:	learn: 0.0564157	total: 1m 32s	remaining: 697ms
1588:	learn: 0.0564155	total: 1m 32s	remaining: 639ms
1589:	learn: 0.0564153	total: 1m 32s	remaining: 581ms
1590:	learn: 0.0564152	total: 1m 32s	remaining: 523ms
1591:	learn: 0.0564150	total: 1m 32s	remaining: 465ms
1592:	learn: 0.0564148	total: 1m 32s	remaining: 406ms
1593:	learn: 0.0564145	total: 1m 32s	remaining: 348ms
1594:	learn: 0.0564143	total: 1m 32s	remaining: 290ms
1595:	learn: 0.0564141	total: 1m 32s	remaining: 232ms
1596:	learn: 0.0564139	total: 1m 32s	remaining: 174ms
1597:	learn: 0.0564136	total: 1m 32s	remaining: 116ms
1598:	learn: 0.0564134	total: 1m 32s	remaining: 58ms
1599:	learn: 0.0564133	total: 1m 32s	remaining: 0us

In [32]:
cat = CatBoostRegressor(
    subsample=1.0,
    random_strength=5,
    min_data_in_leaf=10,
    learning_rate=0.1,
    leaf_estimation_iterations=1,
    l2_leaf_reg=5,
    iterations=800,
    grow_policy='SymmetricTree',
    depth=7,
    border_count=128,
    bootstrap_type='MVS',
    bagging_temperature=0.5
)
cat.fit(X_train, y_train)
y_pred = cat.predict(X_test)

print('MSE for catboost:', mean_squared_error(y_test, y_pred))
print('R2 for catboost:', r2_score(y_test, y_pred))

0:	learn: 0.1528891	total: 54.6ms	remaining: 43.6s
1:	learn: 0.1408864	total: 94.2ms	remaining: 37.6s
2:	learn: 0.1306697	total: 122ms	remaining: 32.5s
3:	learn: 0.1204629	total: 163ms	remaining: 32.5s
4:	learn: 0.1114676	total: 200ms	remaining: 31.7s
5:	learn: 0.1035307	total: 236ms	remaining: 31.2s
6:	learn: 0.0966303	total: 273ms	remaining: 30.9s
7:	learn: 0.0906715	total: 310ms	remaining: 30.7s
8:	learn: 0.0854478	total: 353ms	remaining: 31s
9:	learn: 0.0814030	total: 390ms	remaining: 30.8s
10:	learn: 0.0777586	total: 428ms	remaining: 30.7s
11:	learn: 0.0745660	total: 460ms	remaining: 30.2s
12:	learn: 0.0717214	total: 498ms	remaining: 30.1s
13:	learn: 0.0692291	total: 535ms	remaining: 30s
14:	learn: 0.0671523	total: 573ms	remaining: 30s
15:	learn: 0.0655102	total: 610ms	remaining: 29.9s
16:	learn: 0.0641128	total: 647ms	remaining: 29.8s
17:	learn: 0.0628788	total: 684ms	remaining: 29.7s
18:	learn: 0.0619514	total: 720ms	remaining: 29.6s
19:	learn: 0.0611610	total: 756ms	remaining: 29.5s
20:	learn: 0.0605142	total: 792ms	remaining: 29.4s
21:	learn: 0.0599738	total: 832ms	remaining: 29.4s
22:	learn: 0.0594570	total: 870ms	remaining: 29.4s
23:	learn: 0.0590087	total: 909ms	remaining: 29.4s
24:	learn: 0.0587018	total: 946ms	remaining: 29.3s
25:	learn: 0.0583784	total: 981ms	remaining: 29.2s
26:	learn: 0.0581148	total: 1.02s	remaining: 29.1s
27:	learn: 0.0579144	total: 1.05s	remaining: 29s
28:	learn: 0.0577491	total: 1.09s	remaining: 29s
29:	learn: 0.0576052	total: 1.13s	remaining: 29s
30:	learn: 0.0574924	total: 1.17s	remaining: 29.1s
31:	learn: 0.0574181	total: 1.2s	remaining: 28.8s
32:	learn: 0.0573326	total: 1.24s	remaining: 28.7s
33:	learn: 0.0572557	total: 1.27s	remaining: 28.7s
34:	learn: 0.0571830	total: 1.31s	remaining: 28.7s
35:	learn: 0.0571107	total: 1.35s	remaining: 28.6s
36:	learn: 0.0570603	total: 1.38s	remaining: 28.6s
37:	learn: 0.0570137	total: 1.42s	remaining: 28.5s
38:	learn: 0.0569618	total: 1.46s	remaining: 28.4s
39:	learn: 0.0569119	total: 1.49s	remaining: 28.4s
40:	learn: 0.0568772	total: 1.53s	remaining: 28.3s
41:	learn: 0.0568384	total: 1.57s	remaining: 28.3s
42:	learn: 0.0568034	total: 1.6s	remaining: 28.2s
43:	learn: 0.0567811	total: 1.64s	remaining: 28.2s
44:	learn: 0.0567625	total: 1.68s	remaining: 28.2s
45:	learn: 0.0567411	total: 1.72s	remaining: 28.1s
46:	learn: 0.0567272	total: 1.75s	remaining: 28.1s
47:	learn: 0.0567150	total: 1.79s	remaining: 28.1s
48:	learn: 0.0567057	total: 1.83s	remaining: 28.1s
49:	learn: 0.0566899	total: 1.87s	remaining: 28s
50:	learn: 0.0566736	total: 1.91s	remaining: 28s
51:	learn: 0.0566623	total: 1.94s	remaining: 27.9s
52:	learn: 0.0566511	total: 1.98s	remaining: 27.9s
53:	learn: 0.0566495	total: 2s	remaining: 27.6s
54:	learn: 0.0566377	total: 2.04s	remaining: 27.6s
55:	learn: 0.0566269	total: 2.07s	remaining: 27.5s
56:	learn: 0.0566205	total: 2.1s	remaining: 27.4s
57:	learn: 0.0566069	total: 2.14s	remaining: 27.4s
58:	learn: 0.0566025	total: 2.17s	remaining: 27.2s
59:	learn: 0.0565880	total: 2.2s	remaining: 27.2s
60:	learn: 0.0565830	total: 2.24s	remaining: 27.1s
61:	learn: 0.0565718	total: 2.27s	remaining: 27s
62:	learn: 0.0565676	total: 2.31s	remaining: 27s
63:	learn: 0.0565623	total: 2.34s	remaining: 27s
64:	learn: 0.0565588	total: 2.38s	remaining: 27s
65:	learn: 0.0565546	total: 2.42s	remaining: 26.9s
66:	learn: 0.0565511	total: 2.45s	remaining: 26.8s
67:	learn: 0.0565413	total: 2.49s	remaining: 26.8s
68:	learn: 0.0565295	total: 2.53s	remaining: 26.8s
69:	learn: 0.0565263	total: 2.57s	remaining: 26.8s
70:	learn: 0.0565172	total: 2.6s	remaining: 26.7s
71:	learn: 0.0565121	total: 2.64s	remaining: 26.7s
72:	learn: 0.0565084	total: 2.67s	remaining: 26.6s
73:	learn: 0.0565018	total: 2.71s	remaining: 26.6s
74:	learn: 0.0564957	total: 2.75s	remaining: 26.6s
75:	learn: 0.0564943	total: 2.78s	remaining: 26.5s
76:	learn: 0.0564883	total: 2.82s	remaining: 26.5s
77:	learn: 0.0564848	total: 2.86s	remaining: 26.5s
78:	learn: 0.0564762	total: 2.9s	remaining: 26.4s
79:	learn: 0.0564752	total: 2.93s	remaining: 26.4s
80:	learn: 0.0564690	total: 2.97s	remaining: 26.3s
81:	learn: 0.0564619	total: 3s	remaining: 26.3s
82:	learn: 0.0564581	total: 3.04s	remaining: 26.3s
83:	learn: 0.0564552	total: 3.08s	remaining: 26.2s
84:	learn: 0.0564546	total: 3.1s	remaining: 26.1s
85:	learn: 0.0564514	total: 3.13s	remaining: 26s
86:	learn: 0.0564499	total: 3.17s	remaining: 26s
87:	learn: 0.0564477	total: 3.21s	remaining: 25.9s
88:	learn: 0.0564464	total: 3.24s	remaining: 25.9s
89:	learn: 0.0564425	total: 3.28s	remaining: 25.9s
90:	learn: 0.0564396	total: 3.32s	remaining: 25.9s
91:	learn: 0.0564372	total: 3.35s	remaining: 25.8s
92:	learn: 0.0564351	total: 3.39s	remaining: 25.8s
93:	learn: 0.0564348	total: 3.41s	remaining: 25.6s
94:	learn: 0.0564344	total: 3.45s	remaining: 25.6s
95:	learn: 0.0564311	total: 3.49s	remaining: 25.6s
96:	learn: 0.0564293	total: 3.53s	remaining: 25.6s
97:	learn: 0.0564280	total: 3.56s	remaining: 25.5s
98:	learn: 0.0564261	total: 3.6s	remaining: 25.5s
99:	learn: 0.0564236	total: 3.64s	remaining: 25.5s
100:	learn: 0.0564221	total: 3.68s	remaining: 25.5s
101:	learn: 0.0564176	total: 3.72s	remaining: 25.5s
102:	learn: 0.0564173	total: 3.75s	remaining: 25.4s
103:	learn: 0.0564143	total: 3.78s	remaining: 25.3s
104:	learn: 0.0564132	total: 3.82s	remaining: 25.3s
105:	learn: 0.0564104	total: 3.86s	remaining: 25.3s
106:	learn: 0.0564040	total: 3.9s	remaining: 25.2s
107:	learn: 0.0564021	total: 3.93s	remaining: 25.2s
108:	learn: 0.0564006	total: 3.97s	remaining: 25.2s
109:	learn: 0.0563984	total: 4.01s	remaining: 25.1s
110:	learn: 0.0563962	total: 4.04s	remaining: 25.1s
111:	learn: 0.0563925	total: 4.08s	remaining: 25.1s
112:	learn: 0.0563922	total: 4.11s	remaining: 25s
113:	learn: 0.0563921	total: 4.14s	remaining: 24.9s
114:	learn: 0.0563914	total: 4.17s	remaining: 24.9s
115:	learn: 0.0563897	total: 4.21s	remaining: 24.8s
116:	learn: 0.0563888	total: 4.25s	remaining: 24.8s
117:	learn: 0.0563859	total: 4.29s	remaining: 24.8s
118:	learn: 0.0563805	total: 4.33s	remaining: 24.8s
119:	learn: 0.0563772	total: 4.36s	remaining: 24.7s
120:	learn: 0.0563769	total: 4.39s	remaining: 24.6s
121:	learn: 0.0563769	total: 4.41s	remaining: 24.5s
122:	learn: 0.0563716	total: 4.45s	remaining: 24.5s
123:	learn: 0.0563674	total: 4.49s	remaining: 24.5s
124:	learn: 0.0563656	total: 4.52s	remaining: 24.4s
125:	learn: 0.0563645	total: 4.56s	remaining: 24.4s
126:	learn: 0.0563645	total: 4.58s	remaining: 24.3s
127:	learn: 0.0563592	total: 4.61s	remaining: 24.2s
128:	learn: 0.0563544	total: 4.64s	remaining: 24.2s
129:	learn: 0.0563494	total: 4.68s	remaining: 24.1s
130:	learn: 0.0563490	total: 4.71s	remaining: 24s
131:	learn: 0.0563470	total: 4.74s	remaining: 24s
132:	learn: 0.0563434	total: 4.78s	remaining: 24s
133:	learn: 0.0563384	total: 4.82s	remaining: 23.9s
134:	learn: 0.0563353	total: 4.85s	remaining: 23.9s
135:	learn: 0.0563333	total: 4.89s	remaining: 23.9s
136:	learn: 0.0563291	total: 4.93s	remaining: 23.9s
137:	learn: 0.0563253	total: 4.97s	remaining: 23.8s
138:	learn: 0.0563220	total: 5s	remaining: 23.8s
139:	learn: 0.0563146	total: 5.03s	remaining: 23.7s
140:	learn: 0.0563119	total: 5.07s	remaining: 23.7s
141:	learn: 0.0563059	total: 5.11s	remaining: 23.7s
142:	learn: 0.0563031	total: 5.15s	remaining: 23.7s
143:	learn: 0.0563003	total: 5.19s	remaining: 23.6s
144:	learn: 0.0562968	total: 5.22s	remaining: 23.6s
145:	learn: 0.0562910	total: 5.26s	remaining: 23.6s
146:	learn: 0.0562860	total: 5.3s	remaining: 23.5s
147:	learn: 0.0562798	total: 5.33s	remaining: 23.5s
148:	learn: 0.0562736	total: 5.37s	remaining: 23.5s
149:	learn: 0.0562695	total: 5.4s	remaining: 23.4s
150:	learn: 0.0562661	total: 5.43s	remaining: 23.4s
151:	learn: 0.0562622	total: 5.46s	remaining: 23.3s
152:	learn: 0.0562579	total: 5.5s	remaining: 23.3s
153:	learn: 0.0562535	total: 5.53s	remaining: 23.2s
154:	learn: 0.0562481	total: 5.57s	remaining: 23.2s
155:	learn: 0.0562447	total: 5.6s	remaining: 23.1s
156:	learn: 0.0562410	total: 5.63s	remaining: 23.1s
157:	learn: 0.0562363	total: 5.67s	remaining: 23s
158:	learn: 0.0562320	total: 5.7s	remaining: 23s
159:	learn: 0.0562279	total: 5.74s	remaining: 23s
160:	learn: 0.0562250	total: 5.77s	remaining: 22.9s
161:	learn: 0.0562213	total: 5.81s	remaining: 22.9s
162:	learn: 0.0562182	total: 5.84s	remaining: 22.8s
163:	learn: 0.0562156	total: 5.88s	remaining: 22.8s
164:	learn: 0.0562116	total: 5.91s	remaining: 22.8s
165:	learn: 0.0562083	total: 5.95s	remaining: 22.7s
166:	learn: 0.0562043	total: 5.99s	remaining: 22.7s
167:	learn: 0.0562005	total: 6.02s	remaining: 22.6s
168:	learn: 0.0561971	total: 6.06s	remaining: 22.6s
169:	learn: 0.0561910	total: 6.09s	remaining: 22.6s
170:	learn: 0.0561869	total: 6.13s	remaining: 22.6s
171:	learn: 0.0561836	total: 6.17s	remaining: 22.5s
172:	learn: 0.0561798	total: 6.2s	remaining: 22.5s
173:	learn: 0.0561771	total: 6.24s	remaining: 22.4s
174:	learn: 0.0561734	total: 6.27s	remaining: 22.4s
175:	learn: 0.0561695	total: 6.31s	remaining: 22.4s
176:	learn: 0.0561654	total: 6.34s	remaining: 22.3s
177:	learn: 0.0561625	total: 6.38s	remaining: 22.3s
178:	learn: 0.0561609	total: 6.41s	remaining: 22.2s
179:	learn: 0.0561584	total: 6.47s	remaining: 22.3s
180:	learn: 0.0561557	total: 6.51s	remaining: 22.3s
181:	learn: 0.0561506	total: 6.57s	remaining: 22.3s
182:	learn: 0.0561473	total: 6.61s	remaining: 22.3s
183:	learn: 0.0561444	total: 6.64s	remaining: 22.2s
184:	learn: 0.0561402	total: 6.67s	remaining: 22.2s
185:	learn: 0.0561373	total: 6.71s	remaining: 22.2s
186:	learn: 0.0561318	total: 6.75s	remaining: 22.1s
187:	learn: 0.0561291	total: 6.78s	remaining: 22.1s
188:	learn: 0.0561267	total: 6.82s	remaining: 22s
189:	learn: 0.0561248	total: 6.86s	remaining: 22s
190:	learn: 0.0561223	total: 6.9s	remaining: 22s
191:	learn: 0.0561200	total: 6.93s	remaining: 22s
192:	learn: 0.0561167	total: 6.97s	remaining: 21.9s
193:	learn: 0.0561143	total: 7.01s	remaining: 21.9s
194:	learn: 0.0561124	total: 7.04s	remaining: 21.8s
195:	learn: 0.0561099	total: 7.07s	remaining: 21.8s
196:	learn: 0.0561030	total: 7.11s	remaining: 21.8s
197:	learn: 0.0561000	total: 7.15s	remaining: 21.7s
198:	learn: 0.0560977	total: 7.18s	remaining: 21.7s
199:	learn: 0.0560955	total: 7.21s	remaining: 21.6s
200:	learn: 0.0560938	total: 7.25s	remaining: 21.6s
201:	learn: 0.0560917	total: 7.29s	remaining: 21.6s
202:	learn: 0.0560902	total: 7.33s	remaining: 21.6s
203:	learn: 0.0560868	total: 7.36s	remaining: 21.5s
204:	learn: 0.0560850	total: 7.4s	remaining: 21.5s
205:	learn: 0.0560833	total: 7.43s	remaining: 21.4s
206:	learn: 0.0560816	total: 7.46s	remaining: 21.4s
207:	learn: 0.0560793	total: 7.5s	remaining: 21.3s
208:	learn: 0.0560770	total: 7.53s	remaining: 21.3s
209:	learn: 0.0560742	total: 7.57s	remaining: 21.3s
210:	learn: 0.0560712	total: 7.61s	remaining: 21.2s
211:	learn: 0.0560696	total: 7.64s	remaining: 21.2s
212:	learn: 0.0560681	total: 7.67s	remaining: 21.1s
213:	learn: 0.0560651	total: 7.71s	remaining: 21.1s
214:	learn: 0.0560630	total: 7.74s	remaining: 21.1s
215:	learn: 0.0560612	total: 7.78s	remaining: 21s
216:	learn: 0.0560570	total: 7.82s	remaining: 21s
217:	learn: 0.0560549	total: 7.85s	remaining: 21s
218:	learn: 0.0560524	total: 7.89s	remaining: 20.9s
219:	learn: 0.0560509	total: 7.92s	remaining: 20.9s
220:	learn: 0.0560480	total: 7.96s	remaining: 20.8s
221:	learn: 0.0560455	total: 7.99s	remaining: 20.8s
222:	learn: 0.0560437	total: 8.03s	remaining: 20.8s
223:	learn: 0.0560417	total: 8.06s	remaining: 20.7s
224:	learn: 0.0560393	total: 8.1s	remaining: 20.7s
225:	learn: 0.0560373	total: 8.13s	remaining: 20.6s
226:	learn: 0.0560355	total: 8.16s	remaining: 20.6s
227:	learn: 0.0560334	total: 8.2s	remaining: 20.6s
228:	learn: 0.0560312	total: 8.24s	remaining: 20.5s
229:	learn: 0.0560293	total: 8.27s	remaining: 20.5s
230:	learn: 0.0560273	total: 8.31s	remaining: 20.5s
231:	learn: 0.0560253	total: 8.34s	remaining: 20.4s
232:	learn: 0.0560235	total: 8.38s	remaining: 20.4s
233:	learn: 0.0560216	total: 8.41s	remaining: 20.3s
234:	learn: 0.0560190	total: 8.45s	remaining: 20.3s
235:	learn: 0.0560134	total: 8.49s	remaining: 20.3s
236:	learn: 0.0560104	total: 8.53s	remaining: 20.3s
237:	learn: 0.0560090	total: 8.56s	remaining: 20.2s
238:	learn: 0.0560073	total: 8.6s	remaining: 20.2s
239:	learn: 0.0560054	total: 8.63s	remaining: 20.1s
240:	learn: 0.0560038	total: 8.67s	remaining: 20.1s
241:	learn: 0.0560015	total: 8.7s	remaining: 20.1s
242:	learn: 0.0559997	total: 8.74s	remaining: 20s
243:	learn: 0.0559979	total: 8.78s	remaining: 20s
244:	learn: 0.0559969	total: 8.81s	remaining: 20s
245:	learn: 0.0559952	total: 8.85s	remaining: 19.9s
246:	learn: 0.0559936	total: 8.88s	remaining: 19.9s
247:	learn: 0.0559925	total: 8.91s	remaining: 19.8s
248:	learn: 0.0559909	total: 8.96s	remaining: 19.8s
249:	learn: 0.0559896	total: 9s	remaining: 19.8s
250:	learn: 0.0559856	total: 9.04s	remaining: 19.8s
251:	learn: 0.0559837	total: 9.09s	remaining: 19.8s
252:	learn: 0.0559818	total: 9.13s	remaining: 19.7s
253:	learn: 0.0559788	total: 9.17s	remaining: 19.7s
254:	learn: 0.0559771	total: 9.2s	remaining: 19.7s
255:	learn: 0.0559760	total: 9.23s	remaining: 19.6s
256:	learn: 0.0559746	total: 9.27s	remaining: 19.6s
257:	learn: 0.0559719	total: 9.3s	remaining: 19.5s
258:	learn: 0.0559702	total: 9.34s	remaining: 19.5s
259:	learn: 0.0559685	total: 9.37s	remaining: 19.5s
260:	learn: 0.0559656	total: 9.41s	remaining: 19.4s
261:	learn: 0.0559638	total: 9.45s	remaining: 19.4s
262:	learn: 0.0559624	total: 9.48s	remaining: 19.4s
263:	learn: 0.0559608	total: 9.52s	remaining: 19.3s
264:	learn: 0.0559564	total: 9.56s	remaining: 19.3s
265:	learn: 0.0559548	total: 9.59s	remaining: 19.3s
266:	learn: 0.0559537	total: 9.63s	remaining: 19.2s
267:	learn: 0.0559515	total: 9.67s	remaining: 19.2s
268:	learn: 0.0559501	total: 9.71s	remaining: 19.2s
269:	learn: 0.0559487	total: 9.74s	remaining: 19.1s
270:	learn: 0.0559471	total: 9.77s	remaining: 19.1s
271:	learn: 0.0559456	total: 9.81s	remaining: 19s
272:	learn: 0.0559443	total: 9.84s	remaining: 19s
273:	learn: 0.0559423	total: 9.88s	remaining: 19s
274:	learn: 0.0559416	total: 9.91s	remaining: 18.9s
275:	learn: 0.0559401	total: 9.94s	remaining: 18.9s
276:	learn: 0.0559386	total: 9.98s	remaining: 18.8s
277:	learn: 0.0559365	total: 10s	remaining: 18.8s
278:	learn: 0.0559340	total: 10s	remaining: 18.8s
279:	learn: 0.0559316	total: 10.1s	remaining: 18.7s
280:	learn: 0.0559294	total: 10.1s	remaining: 18.7s
281:	learn: 0.0559285	total: 10.2s	remaining: 18.6s
282:	learn: 0.0559265	total: 10.2s	remaining: 18.6s
283:	learn: 0.0559251	total: 10.2s	remaining: 18.6s
284:	learn: 0.0559231	total: 10.3s	remaining: 18.5s
285:	learn: 0.0559222	total: 10.3s	remaining: 18.5s
286:	learn: 0.0559202	total: 10.3s	remaining: 18.5s
287:	learn: 0.0559185	total: 10.4s	remaining: 18.4s
288:	learn: 0.0559171	total: 10.4s	remaining: 18.4s
289:	learn: 0.0559159	total: 10.4s	remaining: 18.4s
290:	learn: 0.0559141	total: 10.5s	remaining: 18.3s
291:	learn: 0.0559129	total: 10.5s	remaining: 18.3s
292:	learn: 0.0559114	total: 10.5s	remaining: 18.2s
293:	learn: 0.0559098	total: 10.6s	remaining: 18.2s
294:	learn: 0.0559085	total: 10.6s	remaining: 18.2s
295:	learn: 0.0559073	total: 10.6s	remaining: 18.1s
296:	learn: 0.0559063	total: 10.7s	remaining: 18.1s
297:	learn: 0.0559050	total: 10.7s	remaining: 18s
298:	learn: 0.0559038	total: 10.7s	remaining: 18s
299:	learn: 0.0559014	total: 10.8s	remaining: 18s
300:	learn: 0.0559000	total: 10.8s	remaining: 17.9s
301:	learn: 0.0558983	total: 10.9s	remaining: 17.9s
302:	learn: 0.0558965	total: 10.9s	remaining: 17.9s
303:	learn: 0.0558953	total: 10.9s	remaining: 17.8s
304:	learn: 0.0558937	total: 11s	remaining: 17.8s
305:	learn: 0.0558922	total: 11s	remaining: 17.8s
306:	learn: 0.0558904	total: 11s	remaining: 17.7s
307:	learn: 0.0558869	total: 11.1s	remaining: 17.7s
308:	learn: 0.0558859	total: 11.1s	remaining: 17.6s
309:	learn: 0.0558844	total: 11.1s	remaining: 17.6s
310:	learn: 0.0558827	total: 11.2s	remaining: 17.6s
311:	learn: 0.0558809	total: 11.2s	remaining: 17.5s
312:	learn: 0.0558788	total: 11.2s	remaining: 17.5s
313:	learn: 0.0558773	total: 11.3s	remaining: 17.5s
314:	learn: 0.0558759	total: 11.3s	remaining: 17.4s
315:	learn: 0.0558745	total: 11.4s	remaining: 17.4s
316:	learn: 0.0558728	total: 11.4s	remaining: 17.4s
317:	learn: 0.0558718	total: 11.4s	remaining: 17.3s
318:	learn: 0.0558703	total: 11.5s	remaining: 17.3s
319:	learn: 0.0558686	total: 11.5s	remaining: 17.2s
320:	learn: 0.0558668	total: 11.5s	remaining: 17.2s
321:	learn: 0.0558652	total: 11.6s	remaining: 17.2s
322:	learn: 0.0558636	total: 11.6s	remaining: 17.1s
323:	learn: 0.0558617	total: 11.6s	remaining: 17.1s
324:	learn: 0.0558603	total: 11.7s	remaining: 17.1s
325:	learn: 0.0558592	total: 11.7s	remaining: 17s
326:	learn: 0.0558573	total: 11.8s	remaining: 17s
327:	learn: 0.0558564	total: 11.8s	remaining: 17s
328:	learn: 0.0558552	total: 11.8s	remaining: 16.9s
329:	learn: 0.0558539	total: 11.9s	remaining: 16.9s
330:	learn: 0.0558525	total: 11.9s	remaining: 16.9s
331:	learn: 0.0558511	total: 11.9s	remaining: 16.8s
332:	learn: 0.0558497	total: 12s	remaining: 16.8s
333:	learn: 0.0558487	total: 12s	remaining: 16.8s
334:	learn: 0.0558471	total: 12.1s	remaining: 16.7s
335:	learn: 0.0558450	total: 12.1s	remaining: 16.7s
336:	learn: 0.0558440	total: 12.1s	remaining: 16.7s
337:	learn: 0.0558425	total: 12.2s	remaining: 16.6s
338:	learn: 0.0558414	total: 12.2s	remaining: 16.6s
339:	learn: 0.0558400	total: 12.2s	remaining: 16.5s
340:	learn: 0.0558388	total: 12.3s	remaining: 16.5s
341:	learn: 0.0558377	total: 12.3s	remaining: 16.5s
342:	learn: 0.0558364	total: 12.3s	remaining: 16.4s
343:	learn: 0.0558353	total: 12.4s	remaining: 16.4s
344:	learn: 0.0558342	total: 12.4s	remaining: 16.4s
345:	learn: 0.0558327	total: 12.4s	remaining: 16.3s
346:	learn: 0.0558310	total: 12.5s	remaining: 16.3s
347:	learn: 0.0558300	total: 12.5s	remaining: 16.2s
348:	learn: 0.0558286	total: 12.5s	remaining: 16.2s
349:	learn: 0.0558273	total: 12.6s	remaining: 16.2s
350:	learn: 0.0558260	total: 12.6s	remaining: 16.1s
351:	learn: 0.0558246	total: 12.6s	remaining: 16.1s
352:	learn: 0.0558240	total: 12.7s	remaining: 16.1s
353:	learn: 0.0558217	total: 12.7s	remaining: 16s
354:	learn: 0.0558199	total: 12.8s	remaining: 16s
355:	learn: 0.0558150	total: 12.8s	remaining: 16s
356:	learn: 0.0558119	total: 12.8s	remaining: 15.9s
357:	learn: 0.0558099	total: 12.9s	remaining: 15.9s
358:	learn: 0.0558087	total: 12.9s	remaining: 15.9s
359:	learn: 0.0558077	total: 12.9s	remaining: 15.8s
360:	learn: 0.0558067	total: 13s	remaining: 15.8s
361:	learn: 0.0558056	total: 13s	remaining: 15.7s
362:	learn: 0.0558045	total: 13s	remaining: 15.7s
363:	learn: 0.0558022	total: 13.1s	remaining: 15.7s
364:	learn: 0.0557983	total: 13.1s	remaining: 15.6s
365:	learn: 0.0557976	total: 13.2s	remaining: 15.6s
366:	learn: 0.0557962	total: 13.2s	remaining: 15.6s
367:	learn: 0.0557950	total: 13.2s	remaining: 15.5s
368:	learn: 0.0557938	total: 13.3s	remaining: 15.5s
369:	learn: 0.0557929	total: 13.3s	remaining: 15.5s
370:	learn: 0.0557916	total: 13.4s	remaining: 15.5s
371:	learn: 0.0557906	total: 13.4s	remaining: 15.4s
372:	learn: 0.0557898	total: 13.4s	remaining: 15.4s
373:	learn: 0.0557889	total: 13.5s	remaining: 15.4s
374:	learn: 0.0557878	total: 13.5s	remaining: 15.3s
375:	learn: 0.0557851	total: 13.6s	remaining: 15.3s
376:	learn: 0.0557826	total: 13.6s	remaining: 15.3s
377:	learn: 0.0557812	total: 13.7s	remaining: 15.3s
378:	learn: 0.0557798	total: 13.7s	remaining: 15.2s
379:	learn: 0.0557786	total: 13.8s	remaining: 15.2s
380:	learn: 0.0557769	total: 13.8s	remaining: 15.2s
381:	learn: 0.0557750	total: 13.8s	remaining: 15.1s
382:	learn: 0.0557736	total: 13.9s	remaining: 15.1s
383:	learn: 0.0557716	total: 13.9s	remaining: 15.1s
384:	learn: 0.0557707	total: 14s	remaining: 15s
385:	learn: 0.0557693	total: 14s	remaining: 15s
386:	learn: 0.0557685	total: 14s	remaining: 15s
387:	learn: 0.0557672	total: 14.1s	remaining: 15s
388:	learn: 0.0557659	total: 14.1s	remaining: 14.9s

In [18]:
test_data = pd.read_csv('/kaggle/input/playground-series-s5e10/test.csv')
test_data

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
0,517754,highway,2,0.34,45,night,clear,True,True,afternoon,True,True,1
1,517755,urban,3,0.04,45,dim,foggy,True,False,afternoon,True,False,0
2,517756,urban,2,0.59,35,dim,clear,True,False,afternoon,True,True,1
3,517757,rural,4,0.95,35,daylight,rainy,False,False,afternoon,False,False,2
4,517758,highway,2,0.86,35,daylight,clear,True,False,evening,False,True,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
172580,690334,rural,2,0.01,45,dim,rainy,False,False,afternoon,True,True,2
172581,690335,rural,1,0.74,70,daylight,foggy,False,True,afternoon,False,False,2
172582,690336,urban,2,0.14,70,dim,clear,False,False,evening,True,True,1
172583,690337,urban,1,0.09,45,daylight,foggy,True,True,morning,False,True,0
172584,690338,highway,1,0.63,35,night,foggy,True,False,evening,False,False,0

In [20]:
ids = test_data['id']
Xt_data = test_data.drop(['id'], axis=1)
Xt_data = ctx.transform(Xt_data)

In [21]:
yt_pred = cat.predict(Xt_data)
np.savetxt('output.csv', np.column_stack((ids, yt_pred)), delimiter=',', comments='', header='id,accident_risk', fmt=['%d', '%.2f'])

# Random Forest

In [31]:
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print('MSE for rf:', mean_squared_error(y_test, y_pred))
print('R2 for rf:', r2_score(y_test, y_pred))

MSE for rf: 0.003531438230763739
R2 for rf: 0.8721058458110336

In [128]:
yt_pred = rf.predict(Xt_data)
np.savetxt('output2.csv', np.column_stack((ids, yt_pred)), delimiter=',', comments='', header='id,accident_risk', fmt=['%d', '%.2f'])

# XGB Regressor

In [24]:
xgb = XGBRegressor()
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)

print('MSE for catboost:', mean_squared_error(y_test, y_pred))
print('R2 for catboost:', r2_score(y_test, y_pred))

MSE for catboost: 0.0031665827169747693
R2 for catboost: 0.8853194104518427

In [27]:
from scipy.stats import uniform, randint
param_distributions = {
    'n_estimators': randint(100, 1000),
    'learning_rate': uniform(0.01, 0.3),       # 0.01 to 0.31
    'max_depth': randint(3, 15),
    'min_child_weight': randint(1, 10),
    'subsample': uniform(0.5, 0.5),           # 0.5 to 1.0
    'colsample_bytree': uniform(0.5, 0.5),    # 0.5 to 1.0
    'reg_lambda': uniform(0.1, 10),
    'reg_alpha': uniform(0, 10),
    'gamma': uniform(0, 5),
    'tree_method': ['auto', 'hist']
}

randomCv = RandomizedSearchCV(
    estimator=XGBRegressor(),
    param_distributions=param_distributions,
    cv = 5,
    n_iter=50,
    scoring='neg_mean_squared_error',
    random_state=42,
    n_jobs=-1
)

ctx2 = ColumnTransformer([
    ('cat', cat_pipe, cat_cols),
    ('num', num_pipe, num_cols)
], remainder='passthrough')

X_transformed = ctx2.fit_transform(X)
gcv = randomCv.fit(X_transformed, y, verbose=1)

In [28]:
print('best params:', gcv.best_params_)
print('best score:', gcv.best_score_)

best params: {'colsample_bytree': 0.7838501639099957, 'gamma': 0.15656646227779292, 'learning_rate': 0.26268543237849956, 'max_depth': 14, 'min_child_weight': 2, 'n_estimators': 301, 'reg_alpha': 8.948273504276488, 'reg_lambda': 6.078999788110851, 'subsample': 0.9609371175115584, 'tree_method': 'hist'}
best score: -0.003198566525926625

In [29]:
xgb = XGBRegressor(
    colsample_bytree=0.7838501639099957,
    gamma=0.15656646227779292,
    learning_rate=0.26268543237849956,
    max_depth=14,
    min_child_weight=2,
    n_estimators=301,
    reg_alpha=8.948273504276488,
    reg_lambda=6.078999788110851,
    subsample=0.9609371175115584,
    tree_method='hist',
    objective='reg:squarederror',
    random_state=42
)
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)

print('MSE for catboost:', mean_squared_error(y_test, y_pred))
print('R2 for catboost:', r2_score(y_test, y_pred))

MSE for catboost: 0.003222364811774289
R2 for catboost: 0.88329921262674

In [30]:
yt_pred = xgb.predict(Xt_data)
np.savetxt('output3.csv', np.column_stack((ids, yt_pred)), delimiter=',', comments='', header='id,accident_risk', fmt=['%d', '%.2f'])